### ISSUE TITLE
add primary_sol_number?

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/ldd-msn#4]
So... in Surface_Mission we have start_sol_number and stop_sol_number.  That's all well and good.

However, for mosaics, we don't have start and stop.  We have (from the filename), a "primary" sol number.  This primary is often the end but is explicitly defined to be flexible.  So for example, the insight sis says:

"Primary Sol (or day of year) included in the mosaic.  Nominally, this is the Sol/DOY of the last (in time order, or highest) SCLK input image included in the mosaic.  This can change in off-nominal cases for special circumstances."

We have been putting this in <start_sol_number>.  But that's not really correct.  I'm thinking we need to add a <primary_sol_number> to handle this case...?  Proposed definition:

--

The primary_sol_number is the number of the Mars day that is considered primary, or most important, for this observation.  Landing day is sol 0.  This can be used instead of, or in conjunction with, start_sol_number and end_sol_number.  If used instead of, that indicates that the actual sol range is unspecified.

--

But of course doing this will cause an insight regression... if we switch the template to use primary instead of start for mosaics, then it will change what's in the archive as of whichever release we change.  I'm okay with that, just saying.

**Comment by thareUSGS** [comment]
We could simply update the definition to <start_sol_number>.

Currently: https://github.com/pds-data-dictionaries/ldd-msn/blob/144a9e22470e85918c46e6bc7e53891a7d3d3813/src/PDS4_MSN_IngestLDD.xml#L221

```xml
    <definition>The start_sol_number is the number of the Mars day on which an observation began.
      Landing day is Sol 0.</definition>
```
to something like
```xml
    <definition>The start_sol_number is the number of the Mars day on which an observation began.
      Landing day is Sol 0. When start_sol_number is defined specifically for mosaics, it is considered
      as the Mars day that is considered primary, or most important, for this observation. </definition>
```
just a thought...  granted probably not a good one.

**Comment by rgdeen** [comment]
Not a bad thought, actually.  It would save the insight regression and be less changes overall.  It does preclude future mosaics being able to claim a start and stop as well as a primary though... really, the mosaic programs "should" include start and stop sols, but they don't.  Kind of a bug, but not easily fixable now.  Perhaps revise the definition somewhat:

... Sol 0.  For multi-sol observations, such as mosaics, if start_sol_number is given but stop_sol_number is not, the start_sol_number may instead be interpreted as the primary, or most important, sol for this observation.

Is that better?

**Comment by thareUSGS** [comment]
I think that works. It is a work-around but for derived data sets this has always been a problem (meaning across other metadata standards). I will go forward updating the definition.

**Comment by rgdeen** [comment]
ok

**Comment by thareUSGS** [comment]
v1.2.0.0 updated and re-built.

**Comment by myche** [comment]
Points of ignorance on my part: 

- Do the labels reference the version of the dictionaries used for the relevant label contents?
  - If so, does that alleviate, in some way, the regression assuming that new dictionaries would/might have updated definitions and organization?  This seems like a natural way to allow evolution of both the metadata definitions and its documentation as we understand more along the way.
  - If not, then this seems like situation where we shoehorn and overload items — which seem less than optimal, so I have to assume the former case above would apply.
- The above may not be directly applicable to Bob’s scenario here, so this also brings up my next issue: reprocessing archived data.  Is that allowed, let alone encouraged?
  - If so, then under what circumstances and conditions?  I have always advocated doing so to alleviate the expansion of long-running and long-ignored errata.  So, how would such reprocessing proceed?
    - I'd favor keeping the originally supplied metadata label and then have a "corrected" label that could reflect all the lessons-learned and errata-eradication baked in.
  - If not, then how are such issues corrected without creating yet another errata entry that poses a cognitive load on the user?

I typed up a lot of this earlier this morning, then got side-tracked.  So, I'm now probably sounding like the crazy uncle that _just_ got the joke.

**Comment by rgdeen** [comment]
Labels do specify the dictionary version.  There's a prologue that has all that.  In the case where you're actually using new content in a new DD, that would be important.  In this case, because primary (since discarded, but for argument) would be new, we'd have to do that.  But there are other cases I sent out where the regressions are completely compatible with the old DD too.  So that's a different question.

Reprocessing is allowed, it just means you bump the version number.  We've done that many times on missions (although not yet on pds4).  It's a bit of a PITA though so we tend to avoid it unless it's a substantive change.  As far as I understand it though you have to redeliver the actual data too... versioning the label only is not allowed.  It could, and should, be, but I don't think it is.

**Comment by thareUSGS** [comment]
> versioning the label only is not allowed.

Given the volume of some data releases and the ongoing evolution for PDS4, this is something we will need to continue to push back on. If the data file does not changed (and can be verified using checksums), I don't see an issue versioning labels. If we don't allow for more easily updating or correcting labels we will be in the same boat as PDS3 (where it felt that archives where written in stone and could not be touched).

**Comment by rgdeen** [comment]
I agree, happy to help push if given a forum.
